### ISSUE TITLE
Cannot clone recursive

### ISSUE THREAD

**Issue by noonien** [Gekkio/gb-hardware#2]
When trying to clone the repository, I get several errors similar to this one:

```
Cloning into '/tmp/gb-hardware/GB-BRK-LINK-B/external/kicad-symbols'...
fatal: remote error: 
  Gekkio/gb-hardware.git/external/kicad-symbols is not a valid repository name
  Email support@github.com for help
fatal: clone of 'git@github.com:Gekkio/gb-hardware.git/external/kicad-symbols' into submodule path '/tmp/gb-hardware/GB-BRK-LINK-B/external/kicad-symbols' failed
```

I think the urls for the subrepos might be broken.

**Comment by Gekkio** [comment]
This was caused by me trying to be too clever with submodules...I've reverted that change so now every project has submodules with proper git repository URLs instead of a relative paths. The downside is that the full repository takes a long time to clone and takes a lot of disk space because of duplicate submodules. :crying_cat_face:
